name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Yarn & Node install cache
        uses: EgorDm/gha-yarn-node-cache@v1

      - name: yarn install, and cypress .babelrc config
        timeout-minutes: 10
        run: |
          echo "{\"plugins\": [ \"istanbul\" ]}" > .babelrc
          yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          build: yarn run build
          start: yarn start
          wait-on: http://localhost:1234
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

#       Cypress cover to coveralls
#      - name: Coveralls Action for Cypress tests
#        uses: coverallsapp/github-action@v1.1.2
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path-to-lcov: ./cypress/coverage/lcov.info
#          flag-name: E2e
